services:
  yookassa-to-mynalog:
    container_name: yookassa-to-mynalog
    hostname: yookassa-to-mynalog
    image: grandvan/yookassa-to-mynalog:latest
    restart: always
    volumes:
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1