services:
  yookassa-to-mynalog:
    container_name: yookassa-to-mynalog
    hostname: yookassa-to-mynalog
    image: grandvan/yookassa-to-mynalog:latest
    restart: always
    volumes:
      - ./sync_state.json:/app/sync_state.json
      - ./sync.log:/app/sync.log
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1